### ISSUE TITLE
Add `get_keyword_tags` to dynamic library API and remote interface

### ISSUE THREAD

**Issue by MikkoLeppaaho** [robotframework/jrobotremoteserver#37]
Regarding the Get Keyword Tags -change in RF (https://github.com/robotframework/robotframework/issues/2538)
As you probably had noticed, the remote api in latest robot framework (3.0.2) contains this new feature that is currently not supported by Robot Java Remote Server.  Lack of this support seems not to be a really a big deal at least for our test environments as the only thing at the moment that this causes is the annoying error: ERROR org.apache.xmlrpc.server.XmlRpcErrorLogger - No such handler: get_keyword_tags which visible in the logs. Currently we use the JMSLibrary with the Robot Remote Server.

Of course in the future this support might be handy so if you have any spare time to spend with the project to add this, it would be great :-)

**Comment by pekkaklarck** [comment]
Do you get that error only once or multiple times? If multiple, we should change the Remote library itself to just try once. Please submit an issue to Robot Framework's tracker in that case.

**Comment by MikkoLeppaaho** [comment]
When the remote server is up and running (we use simple bat file to launch it), the error comes each time the pybot (from Ride or cmd line) is launched with test suite that uses the remote library. In our test suites the test suite setup contains keywords that init the jms library connection and that's the first point where remote is used (at least I think so) and that seems to be the exact moment when  error pops up in java remote server.

**Comment by maxdesp** [comment]
I have the same error with robot framework 3.0.2, which version should I use to avoid server crashing on running tests ?

**Comment by ombre42** [comment]
@maxdesp is the server really crashing due to this or is it just an error?

**Comment by moijes12** [comment]
@ombre42 I don't see the server crashing. The called keyword method returns the correct response but the exception trace is still there.

**Comment by karniemi** [comment]
@pekkaklarck @ombre42 @rainmanwy : ...we are seeing the exception 10s/100s of times per test run with jrobotremoteserver...and it is pretty ugly.  It would be really nice if either the method is added to jrobotremoteserver or if the robotframework stopped complaining about it( as the method was supposed to be optional anyway...).

**Comment by MichaelHallik** [comment]
Issue still relevant with RF 3.1.2 (on Python 3.7.6) and jrobotremote 3.0.

EDIT: at my current assignment (Dutch tax authority) this issue is actually a reason for them to abandon the Java database library and promote the Python database lib for any future projects/teams.

**Comment by Hi-Fi** [comment]
Exception should not be there with version 4. 

The response with the call is empty, as JavalibCore is not having annotation to give tags.

**Comment by karniemi** [comment]
> Exception should not be there with version 4.
> 
> The response with the call is empty, as JavalibCore is not having annotation to give tags.

version 4 of which piece of sw?

**Comment by Hi-Fi** [comment]
Jrobotremoteserver 4.0.0

**Comment by Hi-Fi** [comment]
Included in version 4.0.0, closing.
