### ISSUE TITLE
jrobotremoteserver should consider argument as kwarg when only a single map is passed to keyword instead of considering it as normal arg

### ISSUE THREAD

**Issue by shan-96** [robotframework/jrobotremoteserver#49]
Coming from https://github.com/robotframework/JavalibCore/issues/19 and [robotframework documentation](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#free-keyword-arguments-kwargs) as java has no support for explicit kwarg variable, a single map passed on to robot keyword without `**` must also be considered as kwarg.

In `KeywordOverload.java` while collecting arguments `args` is not null with one non empty map but `kwargs` are null. However the case should be exactly opposite

**Comment by Hi-Fi** [comment]
Hmmm... I would say no according linked documentation:
> If a Java keyword accepts kwargs, Robot Framework will automatically pack all arguments in name=value syntax at the end of the keyword call into a Map and pass it to the keyword

**Comment by shan-96** [comment]
Linked to https://github.com/robotframework/JavalibCore/issues/33
