### ISSUE TITLE
Passing dictionary to keyword results in empty Map

### ISSUE THREAD

**Issue by Vance-Turner** [robotframework/jrobotremoteserver#50]
Assume I have this method in my Java library (tested with and without the generics on the Map):
```
 public Map task_with_map(Map<String,Integer> data){
        return data;
    }
```

And I attempt to call it with:

```
*** Test Cases ***
Do Task With Map
    &{myMap} =  create dictionary  a=10  b=12
    Log  ${myMap}  INFO
    ${output}  RL1.task with map  ${myMap}
    should be equal  ${output}   ${myMap}
```

The case fails because the Java library is receiving an empty map. Is this related to robotframework/JavalibCore#33? (I have imported the remote library as RL1)

**Comment by Hi-Fi** [comment]
I think this is directly related to linked issue, and it's just not working without annotationlibrary.
